### ISSUE TITLE
Consistent variable declarations

### ISSUE THREAD

**Issue by Cis112233** [G-lang/Glang#15]
Some languages like java have way to many ways to declare variables. I think you should make it like khanacademy's JS so you can use one way to declare ANY kind of variable this is separate then next idea. Also not having to declare the size of arrays when creating them is a nice thing.

**Comment by Cis112233** [comment]
As in Booleans an integers can all be declared with one type of decleration

**Comment by MikaalSky** [comment]
Some languages like Java have many ways to declare variables because they have many types. Not having that feature makes a programming language kind of eh. A good mix of both would be better, really.

**Comment by Cis112233** [comment]
Yes but making several ways to declare a integer as in having long int and some other thing is a bit silly for small applications

**Comment by Gigabyte-Giant** [comment]
> As in Booleans an integers can all be declared with one type of decleration

In C, booleans *are* integers (`true` is 1, `false` is 0), therefore I'm planning on it being the same in Glang.

> [...] not having to declare the size of arrays [...]

This would indeed make Glang easier to use than some languages, but it's not on the top of my list.

> [...] several ways to declare a integer as in having long int and some other thing is a bit silly for small applications

All integer variable types in Glang, will be declared as `long`s in the C code, that way we don't have to worry about the -32,767 to 32,767 limit that signed integers have in C.

**Comment by MikaalSky** [comment]
> silly for small applications
Not everything is a small application.

**Comment by Cis112233** [comment]
I think glang (no offense) is going to be a small application.

**Comment by MikaalSky** [comment]
![lol k bye](https://20isoverrated.files.wordpress.com/2014/02/k-bye.gif)

**Comment by Gigabyte-Giant** [comment]
So, if I'm reading this correctly, @Cis112233 doesn't want to have to specify types for variables?

**Comment by Cis112233** [comment]
Kind of. Less specific is what I would like. One kind for numbers amd booleans one for strings and one for arraya

On Feb 2, 2016 9:01 AM, Gigabyte Giant <notifications@github.com> wrote:
So, if I'm reading this correctly, @Cis112233 doesn't want to have to specify types for variables?

---

**Comment by Gigabyte-Giant** [comment]
I think this can be closed, even though I didn't really follow along with the recommendation.

As-of https://github.com/G-lang/Glang/commit/00c98e419e770f7c708c4b8d2f75339c8faa7f4d, Glang is going to be a strictly typed language, meaning you'll have to specify a type for each of your variables, as well as a return type for each of your functions.

Thanks for the input.
