### ISSUE TITLE
Use makefiles (or similar) instead of shell scripts

### ISSUE THREAD

**Issue by Gigabyte-Giant** [G-lang/Glang#27]
@Vild suggested this to me at some point, and I really think it's something that should be done.

Not exactly high-priority, but definitely something to do.

**Comment by Vild** [comment]
:+1:

**Comment by Gigabyte-Giant** [comment]
@Vild, since you've kindly decided to +1 this, which should I use; plain 'ol makefiles, or cmake?

**Comment by Vild** [comment]
Makefiles ofc.
Unless you will do crazy stuff with extraction a lot of code into multiple libraries

**Comment by Gigabyte-Giant** [comment]
Yep, agreed. :+1:

**Comment by Gigabyte-Giant** [comment]
I created a basic makefile in https://github.com/G-lang/Glang/commit/7caa5b7aaf57701b34231c57b98a7b333ee6d281.

**Comment by Gigabyte-Giant** [comment]
Closing with https://github.com/G-lang/Glang/commit/88f1e8f170cbf272bc43a68cbaceffc8bfa8e7f2.

**Comment by Vild** [comment]
Nice, but still, Could be more dynamic.
I can show an example later :)

**Comment by Gigabyte-Giant** [comment]
Sounds good @Vild.

**Comment by Vild** [comment]
Kinda like this: https://www.livecoding.tv/pastebin/i4TK
Also it is "Makefile" not "makefile"
